pipeline {
    agent any

    parameters {
        choice choices: ['main', 'master'], description: 'choose branch', name: 'BRANCH'
    }
        
    stages {
        stage('Build') {
            steps {
                echo "BRANCH: ${params.BRANCH}"
                sh 'mvn -B -DskipTests clean install'
            }
        }
    


        stage('SonarQube analysis') { 
            steps {
              withSonarQubeEnv('SonarQube') {
                sh 'mvn sonar:sonar'
            }
        }
    }

        stage('Test') {
            steps {
                sh 'mvn test'
            }
                post {
                    always {
                        junit 'target/surefire-reports/*.xml'
                    }
                }
            }
        }
}
