pipeline {
    agent {
        label 'java_agent'
    }
    parameters {
        
        // Define choice parameter.
        choice (
            name: 'BRANCH',
            choices: 'master\nmain'
            description: 'Choose the branch.'
        )
    }
        
    stages {
        stage('Build') {
            steps {
                echo "BRANCH: ${params.BRANCH}"
                sh 'mvn -B -DskipTests clean install'
            }
        }
    }


    stage("SonarQube analysis") {
            steps {
              withSonarQubeEnv('Sonar') {
                sh 'mvn sonar:sonar'
            }
        }
    }

    stage('Test') {
        steps {
            sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
    }
}
