pipeline {
    agent {
        label 'java_agent'
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean install'
            }
        }


    stage("SonarQube analysis") {
            steps {
              withSonarQubeEnv('My SonarQube Server') {
                sh 'mvn clean package sonar:sonar'
            }
        }
    }

    stage('Test') {
        steps {
            sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
    stage('Deliver') {
        steps {
            sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
